package com.bluezealot.hashmap;

import java.util.ArrayList;
import java.util.List;

public class TestDataSet {
    public static List<String[]> data = new ArrayList<>();
    public static List<String> codes = new ArrayList<>();
    public static List<String[]> usCodes = new ArrayList<>();

    static {
        data.add(new String[]{"010","北京_北京"                                  });
data.add(new String[]{"020","广东_广州市"                                });
data.add(new String[]{"021","上海_上海"                                  });
data.add(new String[]{"022","天津_天津"                                  });
data.add(new String[]{"023","重庆_重庆"                                  });
data.add(new String[]{"024","辽宁_沈阳市"                                });
data.add(new String[]{"025","江苏_南京市"                                });
data.add(new String[]{"027","湖北_武汉市"                                });
data.add(new String[]{"028","四川_眉山市"                                });
data.add(new String[]{"029","陕西_西安市"                                 });
data.add(new String[]{"0310","河北_邯郸市"                                 });
data.add(new String[]{"0311","河北_石家庄市"                                });
data.add(new String[]{"0312","河北_保定市"                                 });
data.add(new String[]{"0313","河北_张家口市"                                });
data.add(new String[]{"0314","河北_承德市"                                 });
data.add(new String[]{"0315","河北_唐山市"                                 });
data.add(new String[]{"0316","河北_廊坊市"                                 });
data.add(new String[]{"0317","河北_沧州市"                                 });
data.add(new String[]{"0318","河北_衡水市"                                 });
data.add(new String[]{"0319","河北_邢台市"                                 });
data.add(new String[]{"0335","河北_秦皇岛市"                                });
data.add(new String[]{"0349","山西_朔州市"                                 });
data.add(new String[]{"0350","山西_忻州市"                                 });
data.add(new String[]{"0351","山西_太原市"                                 });
data.add(new String[]{"0352","山西_大同市"                                 });
data.add(new String[]{"0353","山西_阳泉市"                                 });
data.add(new String[]{"0354","山西_晋中市"                                 });
data.add(new String[]{"0355","山西_长治市"                                 });
data.add(new String[]{"0356","山西_晋城市"                                 });
data.add(new String[]{"0357","山西_临汾市"                                 });
data.add(new String[]{"0358","山西_吕梁市"                                 });
data.add(new String[]{"0359","山西_运城市"                                 });
data.add(new String[]{"0370","河南_商丘市"                                 });
data.add(new String[]{"0371","河南_郑州市"                                 });
data.add(new String[]{"0372","河南_安阳市"                                 });
data.add(new String[]{"0373","河南_新乡市"                                 });
data.add(new String[]{"0374","河南_许昌市"                                 });
data.add(new String[]{"0375","河南_平顶山市"                                });
data.add(new String[]{"0376","河南_信阳市"                                 });
data.add(new String[]{"0377","河南_南阳市"                                 });
data.add(new String[]{"0379","河南_洛阳市"                                 });
data.add(new String[]{"0391","河南_焦作市"                                 });
data.add(new String[]{"0392","河南_鹤壁市"                                 });
data.add(new String[]{"0393","河南_濮阳市"                                 });
data.add(new String[]{"0394","河南_周口市"                                 });
data.add(new String[]{"0395","河南_漯河市"                                 });
data.add(new String[]{"0396","河南_驻马店市"                                });
data.add(new String[]{"0398","河南_三门峡市"                                });
data.add(new String[]{"0410","辽宁_铁岭市"                                 });
data.add(new String[]{"0411","广东_中山市"                                 });
data.add(new String[]{"0412","辽宁_鞍山市"                                 });
data.add(new String[]{"0413","辽宁_抚顺市"                                 });
data.add(new String[]{"0414","辽宁_本溪市"                                 });
data.add(new String[]{"0415","辽宁_丹东市"                                 });
data.add(new String[]{"0416","辽宁_锦州市"                                 });
data.add(new String[]{"0417","辽宁_营口市"                                 });
data.add(new String[]{"0418","辽宁_阜新市"                                 });
data.add(new String[]{"0419","辽宁_辽阳市"                                 });
data.add(new String[]{"0421","辽宁_朝阳市"                                 });
data.add(new String[]{"0427","辽宁_盘锦市"                                 });
data.add(new String[]{"0429","辽宁_葫芦岛市"                                });
data.add(new String[]{"0431","吉林_长春市              "                   });
data.add(new String[]{"0432","吉林_吉林市              "                   });
data.add(new String[]{"0433","吉林_延边               "                    });
data.add(new String[]{"0434","吉林_四平市              "                   });
data.add(new String[]{"0435","吉林_通化市              "                   });
data.add(new String[]{"0436","吉林_白城市              "                   });
data.add(new String[]{"0437","吉林_辽源市              "                   });
data.add(new String[]{"0438","吉林_松原市              "                   });
data.add(new String[]{"0439","吉林_白山市              "                   });
data.add(new String[]{"0451","黑龙江_哈尔滨市           "                   });
data.add(new String[]{"0452","黑龙江_齐齐哈尔市         "                    });
data.add(new String[]{"0453","黑龙江_牡丹江市          "                    });
data.add(new String[]{"0454","黑龙江_佳木斯市          "                    });
data.add(new String[]{"0455","黑龙江_绥化市            "                    });
data.add(new String[]{"0456","黑龙江_黑河市            "                    });
data.add(new String[]{"0457","黑龙江_大兴安岭地区       "                    });
data.add(new String[]{"0458","黑龙江_伊春市            "                    });
data.add(new String[]{"0459","黑龙江_大庆市            "                    });
data.add(new String[]{"0464","黑龙江_七台河市          "                    });
data.add(new String[]{"0467","黑龙江_鸡西市            "                    });
data.add(new String[]{"0468","黑龙江_鹤岗市            "                    });
data.add(new String[]{"0469","黑龙江_双鸭山市          "                    });
data.add(new String[]{"0470","内蒙古_海拉尔            "                    });
data.add(new String[]{"0471","内蒙古_呼和浩特市         "                   });
data.add(new String[]{"0472","内蒙古_包头市            "                    });
data.add(new String[]{"0473","内蒙古_乌海市            "                    });
data.add(new String[]{"0474","内蒙古_乌兰察布          "                    });
data.add(new String[]{"0475","内蒙古_通辽市            "                    });
data.add(new String[]{"0476","内蒙古_赤峰市            "                    });
data.add(new String[]{"0477","内蒙古_鄂尔多斯市         "                    });
data.add(new String[]{"0478","内蒙古_巴彦淖尔市         "                    });
data.add(new String[]{"0479","内蒙古_锡林郭勒          "                    });
data.add(new String[]{"0482","内蒙古_乌兰浩特          "                    });
data.add(new String[]{"0483","内蒙古_阿拉善            "                    });
data.add(new String[]{"0510","江苏_无锡市              "                   });
data.add(new String[]{"0511","江苏_镇江市              "                   });
data.add(new String[]{"0512","江苏_苏州市              "                   });
data.add(new String[]{"0513","江苏_南通市              "                   });
data.add(new String[]{"0514","江苏_扬州市              "                   });
data.add(new String[]{"0515","江苏_盐城市              "                   });
data.add(new String[]{"0516","江苏_徐州市              "                   });
data.add(new String[]{"0517","江苏_淮安市              "                   });
data.add(new String[]{"0518","江苏_连云港市            "                    });
data.add(new String[]{"0519","江苏_常州市              "                   });
data.add(new String[]{"0523","江苏_泰州市              "                   });
data.add(new String[]{"0527","江苏_宿迁市              "                   });
data.add(new String[]{"0530","山东_菏泽市              "                   });
data.add(new String[]{"0531","山东_济南市              "                   });
data.add(new String[]{"0532","山东_青岛市              "                   });
data.add(new String[]{"0533","山东_淄博市              "                   });
data.add(new String[]{"0534","山东_德州市              "                   });
data.add(new String[]{"0535","山东_烟台市              "                   });
data.add(new String[]{"0536","山东_潍坊市              "                   });
data.add(new String[]{"0537","山东_济宁市              "                   });
data.add(new String[]{"0538","山东_泰安市              "                   });
data.add(new String[]{"0539","山东_临沂市              "                   });
data.add(new String[]{"0543","山东_滨州市              "                   });
data.add(new String[]{"0546","山东_东营市              "                   });
data.add(new String[]{"0550","安徽_滁州市              "                   });
data.add(new String[]{"0551","安徽_合肥市              "                   });
data.add(new String[]{"0552","安徽_蚌埠市              "                   });
data.add(new String[]{"0553","安徽_芜湖市              "                   });
data.add(new String[]{"0554","安徽_淮南市              "                   });
data.add(new String[]{"0555","安徽_马鞍山市            "                    });
data.add(new String[]{"0556","安徽_安庆市              "                   });
data.add(new String[]{"0557","安徽_宿州市              "                   });
data.add(new String[]{"0558","安徽_阜阳市              "                   });
data.add(new String[]{"0559","安徽_黄山市              "                   });
data.add(new String[]{"0561","安徽_淮北市              "                   });
data.add(new String[]{"0562","安徽_铜陵市              "                   });
data.add(new String[]{"0563","安徽_宣城市              "                   });
data.add(new String[]{"0564","安徽_六安市              "                   });
data.add(new String[]{"0566","安徽_池州市              "                   });
data.add(new String[]{"0570","浙江_衢州市              "                   });
data.add(new String[]{"0571","浙江_杭州市              "                   });
data.add(new String[]{"0572","浙江_湖州市              "                   });
data.add(new String[]{"0573","浙江_嘉兴市              "                    });
data.add(new String[]{"0574","浙江_宁波市              "                   });
data.add(new String[]{"0575","浙江_绍兴市              "                    });
data.add(new String[]{"0576","浙江_台州市              "                   });
data.add(new String[]{"0577","浙江_温州市              "                   });
data.add(new String[]{"0578","浙江_丽水市              "                   });
data.add(new String[]{"0579","浙江_金华市              "                   });
data.add(new String[]{"0580","浙江_舟山市              "                   });
data.add(new String[]{"0591","福建_福州市              "                   });
data.add(new String[]{"0592","福建_厦门市              "                    });
data.add(new String[]{"0593","福建_宁德市              "                   });
data.add(new String[]{"0594","福建_莆田市              "                   });
data.add(new String[]{"0595","福建_泉州市              "                   });
data.add(new String[]{"0596","福建_漳州市              "                   });
data.add(new String[]{"0597","福建_龙岩市              "                   });
data.add(new String[]{"0598","福建_三明市              "                   });
data.add(new String[]{"0599","福建_南平市              "                   });
data.add(new String[]{"0631","山东_威海市              "                   });
data.add(new String[]{"0632","山东_枣庄市              "                   });
data.add(new String[]{"0633","山东_日照市              "                   });
data.add(new String[]{"0634","山东_莱芜市              "                   });
data.add(new String[]{"0635","山东_聊城市              "                   });
data.add(new String[]{"0660","广东_汕尾市              "                   });
data.add(new String[]{"0662","广东_阳江市              "                   });
data.add(new String[]{"0663","广东_揭阳市              "                   });
data.add(new String[]{"0668","广东_茂名市              "                   });
data.add(new String[]{"0691","云南_西双版纳傣族自治州   "                    });
data.add(new String[]{"0692","云南_德宏傣族景颇族自治州  "                   });
data.add(new String[]{"0701","江西_鹰潭市              "                   });
data.add(new String[]{"0710","湖北_襄阳市              "                   });
data.add(new String[]{"0711","湖北_鄂州市              "                   });
data.add(new String[]{"0712","湖北_孝感市              "                   });
data.add(new String[]{"0713","湖北_黄冈市              "                   });
data.add(new String[]{"0714","湖北_黄石市              "                   });
data.add(new String[]{"0715","湖北_咸宁市              "                   });
data.add(new String[]{"0716","湖北_荆州市              "                    });
data.add(new String[]{"0717","湖北_宜昌市              "                   });
data.add(new String[]{"0718","湖北_恩施土家族苗族自治州  "                   });
data.add(new String[]{"0719","湖北_十堰市              "                   });
data.add(new String[]{"0722","湖北_随州市              "                   });
data.add(new String[]{"0724","湖北_荆门市               "                   });
data.add(new String[]{"0728","湖北_江汉（天门/仙桃/潜江）区"                    });
data.add(new String[]{"0730","湖南_岳阳市              "                   });
data.add(new String[]{"0731","湖南_长沙市              "                   });
data.add(new String[]{"0734","湖南_衡阳市              "                   });
data.add(new String[]{"0735","湖南_郴州市              "                   });
data.add(new String[]{"0736","湖南_常德市              "                   });
data.add(new String[]{"0737","湖南_益阳市              "                   });
data.add(new String[]{"0738","湖南_娄底市              "                   });
data.add(new String[]{"0739","湖南_邵阳市              "                   });
data.add(new String[]{"0743","湖南_吉首市              "                   });
data.add(new String[]{"0744","湖南_张家界市            "                    });
data.add(new String[]{"0745","湖南_怀化市              "                   });
data.add(new String[]{"0746","湖南_永州市              "                   });
data.add(new String[]{"0750","广东_江门市              "                    });
data.add(new String[]{"0751","广东_韶关市              "                   });
data.add(new String[]{"0752","广东_惠州市              "                   });
data.add(new String[]{"0753","广东_梅州市              "                   });
data.add(new String[]{"0754","广东_汕头市              "                   });
data.add(new String[]{"0755","广东_深圳市              "                   });
data.add(new String[]{"0756","广东_珠海市              "                   });
data.add(new String[]{"0757","广东_佛山市              "                   });
data.add(new String[]{"0758","广东_肇庆市              "                   });
data.add(new String[]{"0759","广东_湛江市              "                   });
data.add(new String[]{"0760","广东_中山市              "                   });
data.add(new String[]{"0762","广东_河源市              "                   });
data.add(new String[]{"0763","广东_清远市              "                   });
data.add(new String[]{"0766","广东_云浮市              "                   });
data.add(new String[]{"0768","广东_潮州市              "                   });
data.add(new String[]{"0769","广东_东莞市              "                   });
data.add(new String[]{"0770","广西_防城港市            "                    });
data.add(new String[]{"0771","广西_南宁市              "                   });
data.add(new String[]{"0772","广西_柳州市              "                   });
data.add(new String[]{"0773","广西_桂林市              "                   });
data.add(new String[]{"0774","广西_梧州市              "                   });
data.add(new String[]{"0775","广西_玉林市              "                   });
data.add(new String[]{"0776","广西_百色市              "                   });
data.add(new String[]{"0777","广西_钦州市              "                   });
data.add(new String[]{"0778","广西_河池市              "                   });
data.add(new String[]{"0779","广西_北海市              "                   });
data.add(new String[]{"0790","江西_新余市              "                   });
data.add(new String[]{"0791","江西_南昌市              "                   });
data.add(new String[]{"0792","江西_九江市              "                   });
data.add(new String[]{"0793","江西_上饶市              "                   });
data.add(new String[]{"0794","江西_抚州市              "                   });
data.add(new String[]{"0795","江西_宜春市              "                   });
data.add(new String[]{"0796","江西_吉安市              "                   });
data.add(new String[]{"0797","江西_赣州市              "                   });
data.add(new String[]{"0798","江西_景德镇市            "                    });
data.add(new String[]{"0799","江西_萍乡市              "                   });
data.add(new String[]{"0812","四川_攀枝花市            "                    });
data.add(new String[]{"0813","四川_自贡市              "                   });
data.add(new String[]{"0816","四川_绵阳市              "                   });
data.add(new String[]{"0817","四川_南充市              "                   });
data.add(new String[]{"0818","四川_达州市              "                   });
data.add(new String[]{"0825","四川_遂宁市              "                   });
data.add(new String[]{"0826","四川_广安市              "                   });
data.add(new String[]{"0827","四川_巴中市              "                   });
data.add(new String[]{"0830","四川_泸州市              "                   });
data.add(new String[]{"0831","四川_宜宾市              "                   });
data.add(new String[]{"0832","四川_内江市              "                   });
data.add(new String[]{"0833","四川_乐山市              "                   });
data.add(new String[]{"0834","四川_西昌市              "                   });
data.add(new String[]{"0835","四川_雅安市              "                   });
data.add(new String[]{"0836","四川_甘孜藏族自治州       "                   });
data.add(new String[]{"0837","四川_阿坝藏族羌族自治州   "                    });
data.add(new String[]{"0838","四川_德阳市              "                   });
data.add(new String[]{"0839","四川_广元市              "                   });
data.add(new String[]{"0851","贵州_贵阳市              "                   });
data.add(new String[]{"0852","贵州_遵义市              "                   });
data.add(new String[]{"0853","贵州_安顺市              "                   });
data.add(new String[]{"0854","贵州_黔南布依族苗族自治州  "                   });
data.add(new String[]{"0855","贵州_黔东南苗族侗族自治州  "                   });
data.add(new String[]{"0856","贵州_铜仁市              "                   });
data.add(new String[]{"0857","贵州_毕节市              "                   });
data.add(new String[]{"0858","贵州_六盘水市            "                    });
data.add(new String[]{"0859","贵州_黔西南布依族苗族自治州"                    });
data.add(new String[]{"0870","云南_昭通市               "                  });
data.add(new String[]{"0871","云南_昆明市               "                  });
data.add(new String[]{"0872","云南_大理白族自治州        "                  });
data.add(new String[]{"0873","云南_红河哈尼族彝族自治州   "                  });
data.add(new String[]{"0874","云南_曲靖市               "                  });
data.add(new String[]{"0875","云南_保山市               "                  });
data.add(new String[]{"0876","云南_文山壮族苗族自治州     "                  });
data.add(new String[]{"0877","云南_玉溪市               "                  });
data.add(new String[]{"0878","云南_楚雄彝族自治州        "                  });
data.add(new String[]{"0879","云南_普洱市               "                  });
data.add(new String[]{"0883","云南_临沧市               "                  });
data.add(new String[]{"0886","云南_怒江傈僳族自治州      "                   });
data.add(new String[]{"0887","云南_迪庆藏族自治州        "                  });
data.add(new String[]{"0888","云南_丽江市               "                  });
data.add(new String[]{"0891","西藏_拉萨市               "                  });
data.add(new String[]{"0892","西藏_日喀则市             "                   });
data.add(new String[]{"0893","西藏_山南地区             "                   });
data.add(new String[]{"0894","西藏_林芝市               "                  });
data.add(new String[]{"0895","西藏_昌都市               "                  });
data.add(new String[]{"0896","西藏_那曲地区             "                   });
data.add(new String[]{"0897","西藏_阿里地区             "                   });
data.add(new String[]{"0898","海南_海口市               "                  });
data.add(new String[]{"0899","海南_三亚市               "                  });
data.add(new String[]{"0901","新疆_塔城地区             "                   });
data.add(new String[]{"0902","新疆_哈密地区             "                   });
data.add(new String[]{"0903","新疆_和田地区             "                   });
data.add(new String[]{"0906","新疆_阿勒泰地区            "                  });
data.add(new String[]{"0908","新疆_克孜勒苏柯尔克孜       "                  });
data.add(new String[]{"0909","新疆_博乐                 "                  });
data.add(new String[]{"0911","陕西_延安市               "                  });
data.add(new String[]{"0912","陕西_榆林市               "                   });
data.add(new String[]{"0913","陕西_渭南市               "                  });
data.add(new String[]{"0914","陕西_商洛市               "                  });
data.add(new String[]{"0915","陕西_安康市               "                  });
data.add(new String[]{"0916","陕西_汉中市               "                  });
data.add(new String[]{"0917","陕西_宝鸡市               "                  });
data.add(new String[]{"0919","陕西_铜川市               "                  });
data.add(new String[]{"0930","甘肃_临夏回族自治州        "                  });
data.add(new String[]{"0931","甘肃_兰州市               "                  });
data.add(new String[]{"0932","甘肃_定西市               "                  });
data.add(new String[]{"0933","甘肃_平凉市               "                  });
data.add(new String[]{"0934","甘肃_庆阳市               "                  });
data.add(new String[]{"0935","甘肃_武威市               "                  });
data.add(new String[]{"0936","甘肃_张掖市               "                  });
data.add(new String[]{"0937","甘肃_嘉峪关市             "                   });
data.add(new String[]{"0938","甘肃_天水市               "                  });
data.add(new String[]{"0939","甘肃_陇南市               "                  });
data.add(new String[]{"0941","甘肃_甘南藏族自治州        "                  });
data.add(new String[]{"0943","甘肃_白银市               "                  });
data.add(new String[]{"0951","宁夏_银川市               "                  });
data.add(new String[]{"0952","宁夏_石嘴山市             "                   });
data.add(new String[]{"0953","宁夏_吴忠市               "                  });
data.add(new String[]{"0954","宁夏_固原市               "                  });
data.add(new String[]{"0955","宁夏_中卫市               "                  });
data.add(new String[]{"0970","青海_海北藏族自治州        "                  });
data.add(new String[]{"0971","青海_西宁市               "                  });
data.add(new String[]{"0972","青海_海东                 "                  });
data.add(new String[]{"0973","青海_黄南藏族自治州        "                  });
data.add(new String[]{"0974","青海_共和县               "                  });
data.add(new String[]{"0975","青海_果洛藏族自治州        "                  });
data.add(new String[]{"0976","青海_玉树藏族自治州        "                  });
data.add(new String[]{"0977","青海_德令哈市             "                   });
data.add(new String[]{"0979","青海_格尔木               "                   });
data.add(new String[]{"0990","新疆_克拉玛依市            "                  });
data.add(new String[]{"0991","新疆_乌鲁木齐市            "                  });
data.add(new String[]{"0992","新疆_奎屯                 "                  });
data.add(new String[]{"0993","新疆_石河子市             "                   });
data.add(new String[]{"0994","新疆_昌吉回族自治州        "                  });
data.add(new String[]{"0995","新疆_吐鲁番市             "                   });
data.add(new String[]{"0996","新疆_库尔勒               "                   });
data.add(new String[]{"0997","新疆_阿克苏地区            "                  });
data.add(new String[]{"0998","新疆_喀什地区             "                   });
data.add(new String[]{"0999","新疆_伊犁哈萨克自治州      "                   });
usCodes.add(new String[]{"201","	NJ                  "});
usCodes.add(new String[]{"202","	DC                  "});
usCodes.add(new String[]{"203","	CT                  "});
usCodes.add(new String[]{"204","	MANITOBA            "});
usCodes.add(new String[]{"205","	AL                  "});
usCodes.add(new String[]{"206","	WA                  "});
usCodes.add(new String[]{"207","	ME                  "});
usCodes.add(new String[]{"208","	ID                  "});
usCodes.add(new String[]{"209","	CA                  "});
usCodes.add(new String[]{"210","	TX                  "});
usCodes.add(new String[]{"212","	NY                  "});
usCodes.add(new String[]{"213","	CA                  "});
usCodes.add(new String[]{"214","	TX                  "});
usCodes.add(new String[]{"215","	PA                  "});
usCodes.add(new String[]{"216","	OH                  "});
usCodes.add(new String[]{"217","	IL                  "});
usCodes.add(new String[]{"218","	MN                  "});
usCodes.add(new String[]{"219","	IN                  "});
usCodes.add(new String[]{"220","	OH                  "});
usCodes.add(new String[]{"223","	PA                  "});
usCodes.add(new String[]{"224","	IL                  "});
usCodes.add(new String[]{"225","	LA                  "});
usCodes.add(new String[]{"226","	ONTARIO             "});
usCodes.add(new String[]{"228","	MS                  "});
usCodes.add(new String[]{"229","	GA                  "});
usCodes.add(new String[]{"231","	MI                  "});
usCodes.add(new String[]{"234","	OH                  "});
usCodes.add(new String[]{"236","	BRITISH COLUMBIA    "});
usCodes.add(new String[]{"239","	FL                  "});
usCodes.add(new String[]{"240","	MD                  "});
usCodes.add(new String[]{"242","	BAHAMAS             "});
usCodes.add(new String[]{"246","	BARBADOS            "});
usCodes.add(new String[]{"248","	MI                  "});
usCodes.add(new String[]{"249","	ONTARIO             "});
usCodes.add(new String[]{"250","	BRITISH COLUMBIA    "});
usCodes.add(new String[]{"251","	AL                  "});
usCodes.add(new String[]{"252","	NC                  "});
usCodes.add(new String[]{"253","	WA                  "});
usCodes.add(new String[]{"254","	TX                  "});
usCodes.add(new String[]{"256","	AL                  "});
usCodes.add(new String[]{"260","	IN                  "});
usCodes.add(new String[]{"262","	WI                  "});
usCodes.add(new String[]{"264","	ANGUILLA            "});
usCodes.add(new String[]{"267","	PA                  "});
usCodes.add(new String[]{"268","	ANTIGUA/BARBUDA     "});
usCodes.add(new String[]{"269","	MI                  "});
usCodes.add(new String[]{"270","	KY                  "});
usCodes.add(new String[]{"272","	PA                  "});
usCodes.add(new String[]{"276","	VA                  "});
usCodes.add(new String[]{"279","	CA                  "});
usCodes.add(new String[]{"281","	TX                  "});
usCodes.add(new String[]{"284","	BRITISH VIRGIN ISLAN"});
usCodes.add(new String[]{"289","	ONTARIO             "});
usCodes.add(new String[]{"301","	MD                  "});
usCodes.add(new String[]{"302","	DE                  "});
usCodes.add(new String[]{"303","	CO                  "});
usCodes.add(new String[]{"304","	WV                  "});
usCodes.add(new String[]{"305","	FL                  "});
usCodes.add(new String[]{"306","	SASKATCHEWAN        "});
usCodes.add(new String[]{"307","	WY                  "});
usCodes.add(new String[]{"308","	NE                  "});
usCodes.add(new String[]{"309","	IL                  "});
usCodes.add(new String[]{"310","	CA                  "});
usCodes.add(new String[]{"312","	IL                  "});
usCodes.add(new String[]{"313","	MI                  "});
usCodes.add(new String[]{"314","	MO                  "});
usCodes.add(new String[]{"315","	NY                  "});
usCodes.add(new String[]{"316","	KS                  "});
usCodes.add(new String[]{"317","	IN                  "});
usCodes.add(new String[]{"318","	LA                  "});
usCodes.add(new String[]{"319","	IA                  "});
usCodes.add(new String[]{"320","	MN                  "});
usCodes.add(new String[]{"321","	FL                  "});
usCodes.add(new String[]{"323","	CA                  "});
usCodes.add(new String[]{"325","	TX                  "});
usCodes.add(new String[]{"326","	OH                  "});
usCodes.add(new String[]{"330","	OH                  "});
usCodes.add(new String[]{"331","	IL                  "});
usCodes.add(new String[]{"332","	NY                  "});
usCodes.add(new String[]{"334","	AL                  "});
usCodes.add(new String[]{"336","	NC                  "});
usCodes.add(new String[]{"337","	LA                  "});
usCodes.add(new String[]{"339","	MA                  "});
usCodes.add(new String[]{"340","	USVI                "});
usCodes.add(new String[]{"341","	CA                  "});
usCodes.add(new String[]{"343","	ONTARIO             "});
usCodes.add(new String[]{"345","	CAYMAN ISLANDS      "});
usCodes.add(new String[]{"346","	TX                  "});
usCodes.add(new String[]{"347","	NY                  "});
usCodes.add(new String[]{"351","	MA                  "});
usCodes.add(new String[]{"352","	FL                  "});
usCodes.add(new String[]{"360","	WA                  "});
usCodes.add(new String[]{"361","	TX                  "});
usCodes.add(new String[]{"364","	KY                  "});
usCodes.add(new String[]{"365","	ONTARIO             "});
usCodes.add(new String[]{"367","	QUEBEC              "});
usCodes.add(new String[]{"380","	OH                  "});
usCodes.add(new String[]{"385","	UT                  "});
usCodes.add(new String[]{"386","	FL                  "});
usCodes.add(new String[]{"401","	RI                  "});
usCodes.add(new String[]{"402","	NE                  "});
usCodes.add(new String[]{"403","	ALBERTA             "});
usCodes.add(new String[]{"404","	GA                  "});
usCodes.add(new String[]{"405","	OK                  "});
usCodes.add(new String[]{"406","	MT                  "});
usCodes.add(new String[]{"407","	FL                  "});
usCodes.add(new String[]{"408","	CA                  "});
usCodes.add(new String[]{"409","	TX                  "});
usCodes.add(new String[]{"410","	MD                  "});
usCodes.add(new String[]{"412","	PA                  "});
usCodes.add(new String[]{"413","	MA                  "});
usCodes.add(new String[]{"414","	WI                  "});
usCodes.add(new String[]{"415","	CA                  "});
usCodes.add(new String[]{"416","	ONTARIO             "});
usCodes.add(new String[]{"417","	MO                  "});
usCodes.add(new String[]{"418","	QUEBEC              "});
usCodes.add(new String[]{"419","	OH                  "});
usCodes.add(new String[]{"423","	TN                  "});
usCodes.add(new String[]{"424","	CA                  "});
usCodes.add(new String[]{"425","	WA                  "});
usCodes.add(new String[]{"430","	TX                  "});
usCodes.add(new String[]{"431","	MANITOBA            "});
usCodes.add(new String[]{"432","	TX                  "});
usCodes.add(new String[]{"434","	VA                  "});
usCodes.add(new String[]{"435","	UT                  "});
usCodes.add(new String[]{"437","	ONTARIO             "});
usCodes.add(new String[]{"438","	QUEBEC              "});
usCodes.add(new String[]{"440","	OH                  "});
usCodes.add(new String[]{"441","	BERMUDA             "});
usCodes.add(new String[]{"442","	CA                  "});
usCodes.add(new String[]{"443","	MD                  "});
usCodes.add(new String[]{"445","	PA                  "});
usCodes.add(new String[]{"447","	IL                  "});
usCodes.add(new String[]{"448","	FL                  "});
usCodes.add(new String[]{"450","	QUEBEC              "});
usCodes.add(new String[]{"458","	OR                  "});
usCodes.add(new String[]{"463","	IN                  "});
usCodes.add(new String[]{"464","	IL                  "});
usCodes.add(new String[]{"469","	TX                  "});
usCodes.add(new String[]{"470","	GA                  "});
usCodes.add(new String[]{"473","	GRENADA             "});
usCodes.add(new String[]{"474","	SASKATCHEWAN        "});
usCodes.add(new String[]{"475","	CT                  "});
usCodes.add(new String[]{"478","	GA                  "});
usCodes.add(new String[]{"479","	AR                  "});
usCodes.add(new String[]{"480","	AZ                  "});
usCodes.add(new String[]{"484","	PA                  "});
usCodes.add(new String[]{"501","	AR                  "});
usCodes.add(new String[]{"502","	KY                  "});
usCodes.add(new String[]{"503","	OR                  "});
usCodes.add(new String[]{"504","	LA                  "});
usCodes.add(new String[]{"505","	NM                  "});
usCodes.add(new String[]{"506","	NEW BRUNSWICK       "});
usCodes.add(new String[]{"507","	MN                  "});
usCodes.add(new String[]{"508","	MA                  "});
usCodes.add(new String[]{"509","	WA                  "});
usCodes.add(new String[]{"510","	CA                  "});
usCodes.add(new String[]{"512","	TX                  "});
usCodes.add(new String[]{"513","	OH                  "});
usCodes.add(new String[]{"514","	QUEBEC              "});
usCodes.add(new String[]{"515","	IA                  "});
usCodes.add(new String[]{"516","	FL                  "});
usCodes.add(new String[]{"517","	MI                  "});
usCodes.add(new String[]{"518","	NY                  "});
usCodes.add(new String[]{"519","	ONTARIO             "});
usCodes.add(new String[]{"520","	AZ                  "});
usCodes.add(new String[]{"530","	CA                  "});
usCodes.add(new String[]{"531","	NE                  "});
usCodes.add(new String[]{"534","	WI                  "});
usCodes.add(new String[]{"539","	OK                  "});
usCodes.add(new String[]{"540","	VA                  "});
usCodes.add(new String[]{"541","	OR                  "});
usCodes.add(new String[]{"548","	ONTARIO             "});
usCodes.add(new String[]{"551","	NJ                  "});
usCodes.add(new String[]{"559","	CA                  "});
usCodes.add(new String[]{"561","	FL                  "});
usCodes.add(new String[]{"562","	CA                  "});
usCodes.add(new String[]{"563","	IA                  "});
usCodes.add(new String[]{"564","	WA                  "});
usCodes.add(new String[]{"567","	OH                  "});
usCodes.add(new String[]{"570","	PA                  "});
usCodes.add(new String[]{"571","	VA                  "});
usCodes.add(new String[]{"572","	OK                  "});
usCodes.add(new String[]{"573","	MO                  "});
usCodes.add(new String[]{"574","	IN                  "});
usCodes.add(new String[]{"575","	NM                  "});
usCodes.add(new String[]{"579","	QUEBEC              "});
usCodes.add(new String[]{"580","	OK                  "});
usCodes.add(new String[]{"581","	QUEBEC              "});
usCodes.add(new String[]{"582","	PA                  "});
usCodes.add(new String[]{"585","	NY                  "});
usCodes.add(new String[]{"586","	MI                  "});
usCodes.add(new String[]{"587","	ALBERTA             "});
usCodes.add(new String[]{"601","	MS                  "});
usCodes.add(new String[]{"602","	AZ                  "});
usCodes.add(new String[]{"603","	NH                  "});
usCodes.add(new String[]{"604","	BRITISH COLUMBIA    "});
usCodes.add(new String[]{"605","	SD                  "});
usCodes.add(new String[]{"606","	KY                  "});
usCodes.add(new String[]{"607","	NY                  "});
usCodes.add(new String[]{"608","	WI                  "});
usCodes.add(new String[]{"609","	NJ                  "});
usCodes.add(new String[]{"610","	PA                  "});
usCodes.add(new String[]{"612","	MN                  "});
usCodes.add(new String[]{"613","	ONTARIO             "});
usCodes.add(new String[]{"614","	OH                  "});
usCodes.add(new String[]{"615","	TN                  "});
usCodes.add(new String[]{"616","	MI                  "});
usCodes.add(new String[]{"617","	MA                  "});
usCodes.add(new String[]{"618","	IL                  "});
usCodes.add(new String[]{"619","	CA                  "});
usCodes.add(new String[]{"620","	KS                  "});
usCodes.add(new String[]{"623","	AZ                  "});
usCodes.add(new String[]{"626","	CA                  "});
usCodes.add(new String[]{"628","	CA                  "});
usCodes.add(new String[]{"629","	TN                  "});
usCodes.add(new String[]{"630","	IL                  "});
usCodes.add(new String[]{"631","	NY                  "});
usCodes.add(new String[]{"636","	MO                  "});
usCodes.add(new String[]{"639","	SASKATCHEWAN        "});
usCodes.add(new String[]{"640","	NJ                  "});
usCodes.add(new String[]{"641","	IA                  "});
usCodes.add(new String[]{"646","	NY                  "});
usCodes.add(new String[]{"647","	ONTARIO             "});
usCodes.add(new String[]{"649","	TURKS & CAICOS ISLAN"});
usCodes.add(new String[]{"650","	CA                  "});
usCodes.add(new String[]{"651","	MN                  "});
usCodes.add(new String[]{"657","	CA                  "});
usCodes.add(new String[]{"658","	JAMAICA             "});
usCodes.add(new String[]{"659","	AL                  "});
usCodes.add(new String[]{"660","	MO                  "});
usCodes.add(new String[]{"661","	CA                  "});
usCodes.add(new String[]{"662","	MS                  "});
usCodes.add(new String[]{"664","	MONTSERRAT          "});
usCodes.add(new String[]{"667","	MD                  "});
usCodes.add(new String[]{"669","	CA                  "});
usCodes.add(new String[]{"670","	CNMI                "});
usCodes.add(new String[]{"671","	GU                  "});
usCodes.add(new String[]{"672","	BRITISH COLUMBIA    "});
usCodes.add(new String[]{"678","	GA                  "});
usCodes.add(new String[]{"680","	NY                  "});
usCodes.add(new String[]{"681","	WV                  "});
usCodes.add(new String[]{"682","	TX                  "});
usCodes.add(new String[]{"684","	AS                  "});
usCodes.add(new String[]{"689","	FL                  "});
usCodes.add(new String[]{"701","	ND                  "});
usCodes.add(new String[]{"702","	NV                  "});
usCodes.add(new String[]{"703","	VA                  "});
usCodes.add(new String[]{"704","	NC                  "});
usCodes.add(new String[]{"705","	ONTARIO             "});
usCodes.add(new String[]{"706","	GA                  "});
usCodes.add(new String[]{"707","	CA                  "});
usCodes.add(new String[]{"708","	IL                  "});
usCodes.add(new String[]{"709","	NEWFOUNDLAND AND LAB"});
usCodes.add(new String[]{"712","	IA                  "});
usCodes.add(new String[]{"713","	TX                  "});
usCodes.add(new String[]{"714","	CA                  "});
usCodes.add(new String[]{"715","	WI                  "});
usCodes.add(new String[]{"716","	NY                  "});
usCodes.add(new String[]{"717","	PA                  "});
usCodes.add(new String[]{"718","	NY                  "});
usCodes.add(new String[]{"719","	CO                  "});
usCodes.add(new String[]{"720","	CO                  "});
usCodes.add(new String[]{"721","	SINT MAARTEN        "});
usCodes.add(new String[]{"724","	PA                  "});
usCodes.add(new String[]{"725","	NV                  "});
usCodes.add(new String[]{"726","	TX                  "});
usCodes.add(new String[]{"727","	FL                  "});
usCodes.add(new String[]{"731","	TN                  "});
usCodes.add(new String[]{"732","	NJ                  "});
usCodes.add(new String[]{"734","	MI                  "});
usCodes.add(new String[]{"737","	TX                  "});
usCodes.add(new String[]{"740","	OH                  "});
usCodes.add(new String[]{"742","	ONTARIO             "});
usCodes.add(new String[]{"743","	NC                  "});
usCodes.add(new String[]{"747","	CA                  "});
usCodes.add(new String[]{"754","	FL                  "});
usCodes.add(new String[]{"757","	VA                  "});
usCodes.add(new String[]{"758","	ST. LUCIA           "});
usCodes.add(new String[]{"760","	CA                  "});
usCodes.add(new String[]{"762","	GA                  "});
usCodes.add(new String[]{"763","	MN                  "});
usCodes.add(new String[]{"765","	IN                  "});
usCodes.add(new String[]{"767","	DOMINICA            "});
usCodes.add(new String[]{"769","	MS                  "});
usCodes.add(new String[]{"770","	GA                  "});
usCodes.add(new String[]{"771","	DC                  "});
usCodes.add(new String[]{"772","	FL                  "});
usCodes.add(new String[]{"773","	IL                  "});
usCodes.add(new String[]{"774","	MA                  "});
usCodes.add(new String[]{"775","	NV                  "});
usCodes.add(new String[]{"778","	BRITISH COLUMBIA    "});
usCodes.add(new String[]{"779","	IL                  "});
usCodes.add(new String[]{"780","	ALBERTA             "});
usCodes.add(new String[]{"781","	MA                  "});
usCodes.add(new String[]{"782","	NOVA SCOTIA - PRINCE"});
usCodes.add(new String[]{"784","	ST. VINCENT & GRENAD"});
usCodes.add(new String[]{"785","	KS                  "});
usCodes.add(new String[]{"786","	FL                  "});
usCodes.add(new String[]{"787","	PUERTO RICO         "});
usCodes.add(new String[]{"801","	UT                  "});
usCodes.add(new String[]{"802","	VT                  "});
usCodes.add(new String[]{"803","	SC                  "});
usCodes.add(new String[]{"804","	VA                  "});
usCodes.add(new String[]{"805","	CA                  "});
usCodes.add(new String[]{"806","	TX                  "});
usCodes.add(new String[]{"807","	ONTARIO             "});
usCodes.add(new String[]{"808","	HI                  "});
usCodes.add(new String[]{"809","	DOMINICAN REPUBLIC  "});
usCodes.add(new String[]{"810","	MI                  "});
usCodes.add(new String[]{"812","	IN                  "});
usCodes.add(new String[]{"813","	FL                  "});
usCodes.add(new String[]{"814","	PA                  "});
usCodes.add(new String[]{"815","	IL                  "});
usCodes.add(new String[]{"816","	MO                  "});
usCodes.add(new String[]{"817","	TX                  "});
usCodes.add(new String[]{"818","	CA                  "});
usCodes.add(new String[]{"819","	QUEBEC              "});
usCodes.add(new String[]{"820","	CA                  "});
usCodes.add(new String[]{"825","	ALBERTA             "});
usCodes.add(new String[]{"828","	NC                  "});
usCodes.add(new String[]{"829","	DOMINICAN REPUBLIC  "});
usCodes.add(new String[]{"830","	TX                  "});
usCodes.add(new String[]{"831","	CA                  "});
usCodes.add(new String[]{"832","	TX                  "});
usCodes.add(new String[]{"838","	NY                  "});
usCodes.add(new String[]{"839","	SC                  "});
usCodes.add(new String[]{"840","	CA                  "});
usCodes.add(new String[]{"843","	SC                  "});
usCodes.add(new String[]{"845","	NY                  "});
usCodes.add(new String[]{"847","	IL                  "});
usCodes.add(new String[]{"848","	NJ                  "});
usCodes.add(new String[]{"849","	DOMINICAN REPUBLIC  "});
usCodes.add(new String[]{"850","	FL                  "});
usCodes.add(new String[]{"854","	SC                  "});
usCodes.add(new String[]{"856","	NJ                  "});
usCodes.add(new String[]{"857","	MA                  "});
usCodes.add(new String[]{"858","	CA                  "});
usCodes.add(new String[]{"859","	KY                  "});
usCodes.add(new String[]{"860","	CT                  "});
usCodes.add(new String[]{"862","	NJ                  "});
usCodes.add(new String[]{"863","	FL                  "});
usCodes.add(new String[]{"864","	SC                  "});
usCodes.add(new String[]{"865","	TN                  "});
usCodes.add(new String[]{"867","	YUKON-NW TERR. - NUN"});
usCodes.add(new String[]{"868","	TRINIDAD & TOBAGO   "});
usCodes.add(new String[]{"869","	ST. KITTS & NEVIS   "});
usCodes.add(new String[]{"870","	AR                  "});
usCodes.add(new String[]{"872","	IL                  "});
usCodes.add(new String[]{"873","	QUEBEC              "});
usCodes.add(new String[]{"876","	JAMAICA             "});
usCodes.add(new String[]{"878","	PA                  "});
usCodes.add(new String[]{"901","	TN                  "});
usCodes.add(new String[]{"902","	NOVA SCOTIA - PRINCE"}); 
usCodes.add(new String[]{"903","	TX                  "});
usCodes.add(new String[]{"904","	FL                  "});
usCodes.add(new String[]{"905","	ONTARIO             "});
usCodes.add(new String[]{"906","	MI                  "});
usCodes.add(new String[]{"907","	AK                  "});
usCodes.add(new String[]{"908","	NJ                  "});
usCodes.add(new String[]{"909","	CA                  "});
usCodes.add(new String[]{"910","	NC                  "});
usCodes.add(new String[]{"912","	GA                  "});
usCodes.add(new String[]{"913","	KS                  "});
usCodes.add(new String[]{"914","	NY                  "});
usCodes.add(new String[]{"915","	TX                  "});
usCodes.add(new String[]{"916","	CA                  "});
usCodes.add(new String[]{"917","	NY                  "});
usCodes.add(new String[]{"918","	OK                  "});
usCodes.add(new String[]{"919","	NC                  "});
usCodes.add(new String[]{"920","	WI                  "});
usCodes.add(new String[]{"925","	CA                  "});
usCodes.add(new String[]{"928","	AZ                  "});
usCodes.add(new String[]{"929","	NY                  "});
usCodes.add(new String[]{"930","	IN                  "});
usCodes.add(new String[]{"931","	TN                  "});
usCodes.add(new String[]{"934","	NY                  "});
usCodes.add(new String[]{"936","	TX                  "});
usCodes.add(new String[]{"937","	OH                  "});
usCodes.add(new String[]{"938","	AL                  "});
usCodes.add(new String[]{"939","	PUERTO RICO         "});
usCodes.add(new String[]{"940","	TX                  "});
usCodes.add(new String[]{"941","	FL                  "});
usCodes.add(new String[]{"945","	TX                  "});
usCodes.add(new String[]{"947","	MI                  "});
usCodes.add(new String[]{"949","	CA                  "});
usCodes.add(new String[]{"951","	CA                  "});
usCodes.add(new String[]{"952","	MN                  "});
usCodes.add(new String[]{"954","	FL                  "});
usCodes.add(new String[]{"956","	TX                  "});
usCodes.add(new String[]{"959","	CT                  "});
usCodes.add(new String[]{"970","	CO                  "});
usCodes.add(new String[]{"971","	OR                  "});
usCodes.add(new String[]{"972","	TX                  "});
usCodes.add(new String[]{"973","	NJ                  "});
usCodes.add(new String[]{"978","	MA                  "});
usCodes.add(new String[]{"979","	TX                  "});
usCodes.add(new String[]{"980","	NC                  "});
usCodes.add(new String[]{"984","	NC                  "});
usCodes.add(new String[]{"985","	LA                  "});
usCodes.add(new String[]{"986","	ID                  "});
usCodes.add(new String[]{"989","	MI                  "});

for(int i = 0; i < usCodes.size(); i ++){
    data.add(usCodes.get(i));
}

for(int i = 0; i < data.size(); i ++){
    codes.add(data.get(i)[0]);
}
    }

}