package com.bluezealot.hashmap;

import java.util.ArrayList;
import java.util.List;

public class TestDataSet {
    public static List<String[]> data = new ArrayList<>();
    public static List<String> codes = new ArrayList<>();

    static {
        data.add(new String[]{"010","北京_北京"                                  });
data.add(new String[]{"020","广东_广州市"                                });
data.add(new String[]{"021","上海_上海"                                  });
data.add(new String[]{"022","天津_天津"                                  });
data.add(new String[]{"023","重庆_重庆"                                  });
data.add(new String[]{"024","辽宁_沈阳市"                                });
data.add(new String[]{"025","江苏_南京市"                                });
data.add(new String[]{"027","湖北_武汉市"                                });
data.add(new String[]{"028","四川_眉山市"                                });
data.add(new String[]{"029","陕西_西安市"                                 });
data.add(new String[]{"0310","河北_邯郸市"                                 });
data.add(new String[]{"0311","河北_石家庄市"                                });
data.add(new String[]{"0312","河北_保定市"                                 });
data.add(new String[]{"0313","河北_张家口市"                                });
data.add(new String[]{"0314","河北_承德市"                                 });
data.add(new String[]{"0315","河北_唐山市"                                 });
data.add(new String[]{"0316","河北_廊坊市"                                 });
data.add(new String[]{"0317","河北_沧州市"                                 });
data.add(new String[]{"0318","河北_衡水市"                                 });
data.add(new String[]{"0319","河北_邢台市"                                 });
data.add(new String[]{"0335","河北_秦皇岛市"                                });
data.add(new String[]{"0349","山西_朔州市"                                 });
data.add(new String[]{"0350","山西_忻州市"                                 });
data.add(new String[]{"0351","山西_太原市"                                 });
data.add(new String[]{"0352","山西_大同市"                                 });
data.add(new String[]{"0353","山西_阳泉市"                                 });
data.add(new String[]{"0354","山西_晋中市"                                 });
data.add(new String[]{"0355","山西_长治市"                                 });
data.add(new String[]{"0356","山西_晋城市"                                 });
data.add(new String[]{"0357","山西_临汾市"                                 });
data.add(new String[]{"0358","山西_吕梁市"                                 });
data.add(new String[]{"0359","山西_运城市"                                 });
data.add(new String[]{"0370","河南_商丘市"                                 });
data.add(new String[]{"0371","河南_郑州市"                                 });
data.add(new String[]{"0372","河南_安阳市"                                 });
data.add(new String[]{"0373","河南_新乡市"                                 });
data.add(new String[]{"0374","河南_许昌市"                                 });
data.add(new String[]{"0375","河南_平顶山市"                                });
data.add(new String[]{"0376","河南_信阳市"                                 });
data.add(new String[]{"0377","河南_南阳市"                                 });
data.add(new String[]{"0379","河南_洛阳市"                                 });
data.add(new String[]{"0391","河南_焦作市"                                 });
data.add(new String[]{"0392","河南_鹤壁市"                                 });
data.add(new String[]{"0393","河南_濮阳市"                                 });
data.add(new String[]{"0394","河南_周口市"                                 });
data.add(new String[]{"0395","河南_漯河市"                                 });
data.add(new String[]{"0396","河南_驻马店市"                                });
data.add(new String[]{"0398","河南_三门峡市"                                });
data.add(new String[]{"0410","辽宁_铁岭市"                                 });
data.add(new String[]{"0411","广东_中山市"                                 });
data.add(new String[]{"0412","辽宁_鞍山市"                                 });
data.add(new String[]{"0413","辽宁_抚顺市"                                 });
data.add(new String[]{"0414","辽宁_本溪市"                                 });
data.add(new String[]{"0415","辽宁_丹东市"                                 });
data.add(new String[]{"0416","辽宁_锦州市"                                 });
data.add(new String[]{"0417","辽宁_营口市"                                 });
data.add(new String[]{"0418","辽宁_阜新市"                                 });
data.add(new String[]{"0419","辽宁_辽阳市"                                 });
data.add(new String[]{"0421","辽宁_朝阳市"                                 });
data.add(new String[]{"0427","辽宁_盘锦市"                                 });
data.add(new String[]{"0429","辽宁_葫芦岛市"                                });
data.add(new String[]{"0431","吉林_长春市              "                   });
data.add(new String[]{"0432","吉林_吉林市              "                   });
data.add(new String[]{"0433","吉林_延边               "                    });
data.add(new String[]{"0434","吉林_四平市              "                   });
data.add(new String[]{"0435","吉林_通化市              "                   });
data.add(new String[]{"0436","吉林_白城市              "                   });
data.add(new String[]{"0437","吉林_辽源市              "                   });
data.add(new String[]{"0438","吉林_松原市              "                   });
data.add(new String[]{"0439","吉林_白山市              "                   });
data.add(new String[]{"0451","黑龙江_哈尔滨市           "                   });
data.add(new String[]{"0452","黑龙江_齐齐哈尔市         "                    });
data.add(new String[]{"0453","黑龙江_牡丹江市          "                    });
data.add(new String[]{"0454","黑龙江_佳木斯市          "                    });
data.add(new String[]{"0455","黑龙江_绥化市            "                    });
data.add(new String[]{"0456","黑龙江_黑河市            "                    });
data.add(new String[]{"0457","黑龙江_大兴安岭地区       "                    });
data.add(new String[]{"0458","黑龙江_伊春市            "                    });
data.add(new String[]{"0459","黑龙江_大庆市            "                    });
data.add(new String[]{"0464","黑龙江_七台河市          "                    });
data.add(new String[]{"0467","黑龙江_鸡西市            "                    });
data.add(new String[]{"0468","黑龙江_鹤岗市            "                    });
data.add(new String[]{"0469","黑龙江_双鸭山市          "                    });
data.add(new String[]{"0470","内蒙古_海拉尔            "                    });
data.add(new String[]{"0471","内蒙古_呼和浩特市         "                   });
data.add(new String[]{"0472","内蒙古_包头市            "                    });
data.add(new String[]{"0473","内蒙古_乌海市            "                    });
data.add(new String[]{"0474","内蒙古_乌兰察布          "                    });
data.add(new String[]{"0475","内蒙古_通辽市            "                    });
data.add(new String[]{"0476","内蒙古_赤峰市            "                    });
data.add(new String[]{"0477","内蒙古_鄂尔多斯市         "                    });
data.add(new String[]{"0478","内蒙古_巴彦淖尔市         "                    });
data.add(new String[]{"0479","内蒙古_锡林郭勒          "                    });
data.add(new String[]{"0482","内蒙古_乌兰浩特          "                    });
data.add(new String[]{"0483","内蒙古_阿拉善            "                    });
data.add(new String[]{"0510","江苏_无锡市              "                   });
data.add(new String[]{"0511","江苏_镇江市              "                   });
data.add(new String[]{"0512","江苏_苏州市              "                   });
data.add(new String[]{"0513","江苏_南通市              "                   });
data.add(new String[]{"0514","江苏_扬州市              "                   });
data.add(new String[]{"0515","江苏_盐城市              "                   });
data.add(new String[]{"0516","江苏_徐州市              "                   });
data.add(new String[]{"0517","江苏_淮安市              "                   });
data.add(new String[]{"0518","江苏_连云港市            "                    });
data.add(new String[]{"0519","江苏_常州市              "                   });
data.add(new String[]{"0523","江苏_泰州市              "                   });
data.add(new String[]{"0527","江苏_宿迁市              "                   });
data.add(new String[]{"0530","山东_菏泽市              "                   });
data.add(new String[]{"0531","山东_济南市              "                   });
data.add(new String[]{"0532","山东_青岛市              "                   });
data.add(new String[]{"0533","山东_淄博市              "                   });
data.add(new String[]{"0534","山东_德州市              "                   });
data.add(new String[]{"0535","山东_烟台市              "                   });
data.add(new String[]{"0536","山东_潍坊市              "                   });
data.add(new String[]{"0537","山东_济宁市              "                   });
data.add(new String[]{"0538","山东_泰安市              "                   });
data.add(new String[]{"0539","山东_临沂市              "                   });
data.add(new String[]{"0543","山东_滨州市              "                   });
data.add(new String[]{"0546","山东_东营市              "                   });
data.add(new String[]{"0550","安徽_滁州市              "                   });
data.add(new String[]{"0551","安徽_合肥市              "                   });
data.add(new String[]{"0552","安徽_蚌埠市              "                   });
data.add(new String[]{"0553","安徽_芜湖市              "                   });
data.add(new String[]{"0554","安徽_淮南市              "                   });
data.add(new String[]{"0555","安徽_马鞍山市            "                    });
data.add(new String[]{"0556","安徽_安庆市              "                   });
data.add(new String[]{"0557","安徽_宿州市              "                   });
data.add(new String[]{"0558","安徽_阜阳市              "                   });
data.add(new String[]{"0559","安徽_黄山市              "                   });
data.add(new String[]{"0561","安徽_淮北市              "                   });
data.add(new String[]{"0562","安徽_铜陵市              "                   });
data.add(new String[]{"0563","安徽_宣城市              "                   });
data.add(new String[]{"0564","安徽_六安市              "                   });
data.add(new String[]{"0566","安徽_池州市              "                   });
data.add(new String[]{"0570","浙江_衢州市              "                   });
data.add(new String[]{"0571","浙江_杭州市              "                   });
data.add(new String[]{"0572","浙江_湖州市              "                   });
data.add(new String[]{"0573","浙江_嘉兴市              "                    });
data.add(new String[]{"0574","浙江_宁波市              "                   });
data.add(new String[]{"0575","浙江_绍兴市              "                    });
data.add(new String[]{"0576","浙江_台州市              "                   });
data.add(new String[]{"0577","浙江_温州市              "                   });
data.add(new String[]{"0578","浙江_丽水市              "                   });
data.add(new String[]{"0579","浙江_金华市              "                   });
data.add(new String[]{"0580","浙江_舟山市              "                   });
data.add(new String[]{"0591","福建_福州市              "                   });
data.add(new String[]{"0592","福建_厦门市              "                    });
data.add(new String[]{"0593","福建_宁德市              "                   });
data.add(new String[]{"0594","福建_莆田市              "                   });
data.add(new String[]{"0595","福建_泉州市              "                   });
data.add(new String[]{"0596","福建_漳州市              "                   });
data.add(new String[]{"0597","福建_龙岩市              "                   });
data.add(new String[]{"0598","福建_三明市              "                   });
data.add(new String[]{"0599","福建_南平市              "                   });
data.add(new String[]{"0631","山东_威海市              "                   });
data.add(new String[]{"0632","山东_枣庄市              "                   });
data.add(new String[]{"0633","山东_日照市              "                   });
data.add(new String[]{"0634","山东_莱芜市              "                   });
data.add(new String[]{"0635","山东_聊城市              "                   });
data.add(new String[]{"0660","广东_汕尾市              "                   });
data.add(new String[]{"0662","广东_阳江市              "                   });
data.add(new String[]{"0663","广东_揭阳市              "                   });
data.add(new String[]{"0668","广东_茂名市              "                   });
data.add(new String[]{"0691","云南_西双版纳傣族自治州   "                    });
data.add(new String[]{"0692","云南_德宏傣族景颇族自治州  "                   });
data.add(new String[]{"0701","江西_鹰潭市              "                   });
data.add(new String[]{"0710","湖北_襄阳市              "                   });
data.add(new String[]{"0711","湖北_鄂州市              "                   });
data.add(new String[]{"0712","湖北_孝感市              "                   });
data.add(new String[]{"0713","湖北_黄冈市              "                   });
data.add(new String[]{"0714","湖北_黄石市              "                   });
data.add(new String[]{"0715","湖北_咸宁市              "                   });
data.add(new String[]{"0716","湖北_荆州市              "                    });
data.add(new String[]{"0717","湖北_宜昌市              "                   });
data.add(new String[]{"0718","湖北_恩施土家族苗族自治州  "                   });
data.add(new String[]{"0719","湖北_十堰市              "                   });
data.add(new String[]{"0722","湖北_随州市              "                   });
data.add(new String[]{"0724","湖北_荆门市               "                   });
data.add(new String[]{"0728","湖北_江汉（天门/仙桃/潜江）区"                    });
data.add(new String[]{"0730","湖南_岳阳市              "                   });
data.add(new String[]{"0731","湖南_长沙市              "                   });
data.add(new String[]{"0734","湖南_衡阳市              "                   });
data.add(new String[]{"0735","湖南_郴州市              "                   });
data.add(new String[]{"0736","湖南_常德市              "                   });
data.add(new String[]{"0737","湖南_益阳市              "                   });
data.add(new String[]{"0738","湖南_娄底市              "                   });
data.add(new String[]{"0739","湖南_邵阳市              "                   });
data.add(new String[]{"0743","湖南_吉首市              "                   });
data.add(new String[]{"0744","湖南_张家界市            "                    });
data.add(new String[]{"0745","湖南_怀化市              "                   });
data.add(new String[]{"0746","湖南_永州市              "                   });
data.add(new String[]{"0750","广东_江门市              "                    });
data.add(new String[]{"0751","广东_韶关市              "                   });
data.add(new String[]{"0752","广东_惠州市              "                   });
data.add(new String[]{"0753","广东_梅州市              "                   });
data.add(new String[]{"0754","广东_汕头市              "                   });
data.add(new String[]{"0755","广东_深圳市              "                   });
data.add(new String[]{"0756","广东_珠海市              "                   });
data.add(new String[]{"0757","广东_佛山市              "                   });
data.add(new String[]{"0758","广东_肇庆市              "                   });
data.add(new String[]{"0759","广东_湛江市              "                   });
data.add(new String[]{"0760","广东_中山市              "                   });
data.add(new String[]{"0762","广东_河源市              "                   });
data.add(new String[]{"0763","广东_清远市              "                   });
data.add(new String[]{"0766","广东_云浮市              "                   });
data.add(new String[]{"0768","广东_潮州市              "                   });
data.add(new String[]{"0769","广东_东莞市              "                   });
data.add(new String[]{"0770","广西_防城港市            "                    });
data.add(new String[]{"0771","广西_南宁市              "                   });
data.add(new String[]{"0772","广西_柳州市              "                   });
data.add(new String[]{"0773","广西_桂林市              "                   });
data.add(new String[]{"0774","广西_梧州市              "                   });
data.add(new String[]{"0775","广西_玉林市              "                   });
data.add(new String[]{"0776","广西_百色市              "                   });
data.add(new String[]{"0777","广西_钦州市              "                   });
data.add(new String[]{"0778","广西_河池市              "                   });
data.add(new String[]{"0779","广西_北海市              "                   });
data.add(new String[]{"0790","江西_新余市              "                   });
data.add(new String[]{"0791","江西_南昌市              "                   });
data.add(new String[]{"0792","江西_九江市              "                   });
data.add(new String[]{"0793","江西_上饶市              "                   });
data.add(new String[]{"0794","江西_抚州市              "                   });
data.add(new String[]{"0795","江西_宜春市              "                   });
data.add(new String[]{"0796","江西_吉安市              "                   });
data.add(new String[]{"0797","江西_赣州市              "                   });
data.add(new String[]{"0798","江西_景德镇市            "                    });
data.add(new String[]{"0799","江西_萍乡市              "                   });
data.add(new String[]{"0812","四川_攀枝花市            "                    });
data.add(new String[]{"0813","四川_自贡市              "                   });
data.add(new String[]{"0816","四川_绵阳市              "                   });
data.add(new String[]{"0817","四川_南充市              "                   });
data.add(new String[]{"0818","四川_达州市              "                   });
data.add(new String[]{"0825","四川_遂宁市              "                   });
data.add(new String[]{"0826","四川_广安市              "                   });
data.add(new String[]{"0827","四川_巴中市              "                   });
data.add(new String[]{"0830","四川_泸州市              "                   });
data.add(new String[]{"0831","四川_宜宾市              "                   });
data.add(new String[]{"0832","四川_内江市              "                   });
data.add(new String[]{"0833","四川_乐山市              "                   });
data.add(new String[]{"0834","四川_西昌市              "                   });
data.add(new String[]{"0835","四川_雅安市              "                   });
data.add(new String[]{"0836","四川_甘孜藏族自治州       "                   });
data.add(new String[]{"0837","四川_阿坝藏族羌族自治州   "                    });
data.add(new String[]{"0838","四川_德阳市              "                   });
data.add(new String[]{"0839","四川_广元市              "                   });
data.add(new String[]{"0851","贵州_贵阳市              "                   });
data.add(new String[]{"0852","贵州_遵义市              "                   });
data.add(new String[]{"0853","贵州_安顺市              "                   });
data.add(new String[]{"0854","贵州_黔南布依族苗族自治州  "                   });
data.add(new String[]{"0855","贵州_黔东南苗族侗族自治州  "                   });
data.add(new String[]{"0856","贵州_铜仁市              "                   });
data.add(new String[]{"0857","贵州_毕节市              "                   });
data.add(new String[]{"0858","贵州_六盘水市            "                    });
data.add(new String[]{"0859","贵州_黔西南布依族苗族自治州"                    });
data.add(new String[]{"0870","云南_昭通市               "                  });
data.add(new String[]{"0871","云南_昆明市               "                  });
data.add(new String[]{"0872","云南_大理白族自治州        "                  });
data.add(new String[]{"0873","云南_红河哈尼族彝族自治州   "                  });
data.add(new String[]{"0874","云南_曲靖市               "                  });
data.add(new String[]{"0875","云南_保山市               "                  });
data.add(new String[]{"0876","云南_文山壮族苗族自治州     "                  });
data.add(new String[]{"0877","云南_玉溪市               "                  });
data.add(new String[]{"0878","云南_楚雄彝族自治州        "                  });
data.add(new String[]{"0879","云南_普洱市               "                  });
data.add(new String[]{"0883","云南_临沧市               "                  });
data.add(new String[]{"0886","云南_怒江傈僳族自治州      "                   });
data.add(new String[]{"0887","云南_迪庆藏族自治州        "                  });
data.add(new String[]{"0888","云南_丽江市               "                  });
data.add(new String[]{"0891","西藏_拉萨市               "                  });
data.add(new String[]{"0892","西藏_日喀则市             "                   });
data.add(new String[]{"0893","西藏_山南地区             "                   });
data.add(new String[]{"0894","西藏_林芝市               "                  });
data.add(new String[]{"0895","西藏_昌都市               "                  });
data.add(new String[]{"0896","西藏_那曲地区             "                   });
data.add(new String[]{"0897","西藏_阿里地区             "                   });
data.add(new String[]{"0898","海南_海口市               "                  });
data.add(new String[]{"0899","海南_三亚市               "                  });
data.add(new String[]{"0901","新疆_塔城地区             "                   });
data.add(new String[]{"0902","新疆_哈密地区             "                   });
data.add(new String[]{"0903","新疆_和田地区             "                   });
data.add(new String[]{"0906","新疆_阿勒泰地区            "                  });
data.add(new String[]{"0908","新疆_克孜勒苏柯尔克孜       "                  });
data.add(new String[]{"0909","新疆_博乐                 "                  });
data.add(new String[]{"0911","陕西_延安市               "                  });
data.add(new String[]{"0912","陕西_榆林市               "                   });
data.add(new String[]{"0913","陕西_渭南市               "                  });
data.add(new String[]{"0914","陕西_商洛市               "                  });
data.add(new String[]{"0915","陕西_安康市               "                  });
data.add(new String[]{"0916","陕西_汉中市               "                  });
data.add(new String[]{"0917","陕西_宝鸡市               "                  });
data.add(new String[]{"0919","陕西_铜川市               "                  });
data.add(new String[]{"0930","甘肃_临夏回族自治州        "                  });
data.add(new String[]{"0931","甘肃_兰州市               "                  });
data.add(new String[]{"0932","甘肃_定西市               "                  });
data.add(new String[]{"0933","甘肃_平凉市               "                  });
data.add(new String[]{"0934","甘肃_庆阳市               "                  });
data.add(new String[]{"0935","甘肃_武威市               "                  });
data.add(new String[]{"0936","甘肃_张掖市               "                  });
data.add(new String[]{"0937","甘肃_嘉峪关市             "                   });
data.add(new String[]{"0938","甘肃_天水市               "                  });
data.add(new String[]{"0939","甘肃_陇南市               "                  });
data.add(new String[]{"0941","甘肃_甘南藏族自治州        "                  });
data.add(new String[]{"0943","甘肃_白银市               "                  });
data.add(new String[]{"0951","宁夏_银川市               "                  });
data.add(new String[]{"0952","宁夏_石嘴山市             "                   });
data.add(new String[]{"0953","宁夏_吴忠市               "                  });
data.add(new String[]{"0954","宁夏_固原市               "                  });
data.add(new String[]{"0955","宁夏_中卫市               "                  });
data.add(new String[]{"0970","青海_海北藏族自治州        "                  });
data.add(new String[]{"0971","青海_西宁市               "                  });
data.add(new String[]{"0972","青海_海东                 "                  });
data.add(new String[]{"0973","青海_黄南藏族自治州        "                  });
data.add(new String[]{"0974","青海_共和县               "                  });
data.add(new String[]{"0975","青海_果洛藏族自治州        "                  });
data.add(new String[]{"0976","青海_玉树藏族自治州        "                  });
data.add(new String[]{"0977","青海_德令哈市             "                   });
data.add(new String[]{"0979","青海_格尔木               "                   });
data.add(new String[]{"0990","新疆_克拉玛依市            "                  });
data.add(new String[]{"0991","新疆_乌鲁木齐市            "                  });
data.add(new String[]{"0992","新疆_奎屯                 "                  });
data.add(new String[]{"0993","新疆_石河子市             "                   });
data.add(new String[]{"0994","新疆_昌吉回族自治州        "                  });
data.add(new String[]{"0995","新疆_吐鲁番市             "                   });
data.add(new String[]{"0996","新疆_库尔勒               "                   });
data.add(new String[]{"0997","新疆_阿克苏地区            "                  });
data.add(new String[]{"0998","新疆_喀什地区             "                   });
data.add(new String[]{"0999","新疆_伊犁哈萨克自治州      "                   });
for(int i = 0; i < data.size(); i ++){
    codes.add(data.get(i)[0]);
}
    }

}